# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.234.0/containers/go/.devcontainer/base.Dockerfile

# VARIANT Defined in devcontainer.json
ARG VARIANT="1.18" 
FROM mcr.microsoft.com/vscode/devcontainers/go:0-${VARIANT}
https://github.com/8Gitbrix/cli/blob/faef89144d895524f1c857232bbbe80986c93520/.devcontainer/Dockerfile
